apiVersion: apps/v1
kind: Deployment
metadata:
  name: sora-website
  namespace: sora-wbsite
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sora-website
  template:
    metadata:
      labels:
        app: sora-website
    spec:
      containers:
        - name: sora-website
          image: 818521988849.dkr.ecr.ap-northeast-2.amazonaws.com/bluerain-gitops-repo:c82b2156829220f4def00ffc892a81a209917985
          ports:
            - containerPort: 80
