apiVersion: apps/v1
kind: Deployment
metadata:
  name: sora-website
  namespace: sora-wbsite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sora-website
  template:
    metadata:
      labels:
        app: sora-website
    spec:
      containers:
        - name: sora-website
          image: 818521988849.dkr.ecr.ap-northeast-2.amazonaws.com/bluerain-gitops-repo:def0e2ed59e37d812778c8b4a5cad7155ddb120f
          ports:
            - containerPort: 80
